var c=!0,aa=null,e=!1,f,g,h,j,ba,ca,k=0,m,n,da=e,ea=c,p,q=e,r=e,s=e,t=e,u=e,v,w,fa=e,ga=e,ha;
window.onload=function(){document.getElementById("book").style.visibility="hidden";document.getElementById("book").style.display="none";document.getElementById("myCanvas3").onmousedown=function(){ja()};document.getElementById("myCanvas3").onmousemove=function(a){ka(a)};document.getElementById("myCanvas3").onmouseup=function(){la()};document.getElementById("myCanvas3").ontouchstart=function(a){a.preventDefault();ja()};document.getElementById("myCanvas3").ontouchmove=function(a){a.preventDefault();
ka(a)};document.getElementById("myCanvas3").ontouchend=function(a){a.preventDefault();la()};document.getElementById("exit").onmousedown=function(){ja()};p=[];w=[];v=[];f=$(window).width();g=$(window).height();h=f>g?g/30:f/30;m=f/2-h/2;n=g/2-h/2;ca=document.getElementById("myCanvas");ca.width=f;ca.height=g;var b=document.getElementById("myCanvas3");b.width=f;b.height=g;ba=b.getContext("2d");j=ca.getContext("2d");var b=0,a=document.getElementById("myCanvas2");a.width=f;a.height=g;a=a.getContext("2d");
a.fillStyle="#c6b4ca";a.fillRect(0,0,f,g);a.d="#000000";for(var d=0;b<=12*h;)a.beginPath(),a.arc(b*Math.cos(d)+(f/2-h/2),b*Math.sin(d)+(g/2-h/2),12*h/20,0,2*Math.PI,c),a.closePath(),a.stroke(),d+=Math.PI/32,d>=2*Math.PI&&(d=0,b+=12*h/20);ma();ha=setInterval(function(){ea&&x()},40);p[0]=new Image;p[0].src="http://cdn4.iconfinder.com/data/icons/brightmix/128/monotone_cog_settings_gear.png";p[1]=new Image;p[1].src="http://cdn1.iconfinder.com/data/icons/defaulticon/icons/png/256x256/media-play-pause-resume.png";
p[2]=new Image;p[2].src="http://icongal.com/gallery/image/6030/network_wireless_wifi.png";p[3]=new Image;p[3].src="http://icons.iconarchive.com/icons/icons-land/metro-raster-sport/256/Trophy-icon.png";p[4]=new Image;p[4].src="http://www.freestockphotos.biz/pictures/14/14376/book.png"};
function ja(){ea=c;fa=e;ga||(k=0);da=ga=c;u=e;"inline"==document.getElementById("book").style.display&&(ha=setInterval(function(){ea&&x()},40));document.getElementById("book").style.a=-1;document.getElementById("book").style.display="none";document.getElementById("exit").style.visibility="hidden";console.log("down")}
function ka(b){var a;if(a=da){a=y(b);var d=A(b),z=0,Q=0,z=a-(f/2-h/2),Q=d-(g/2-h/2);a=Math.sqrt(z*z+Q*Q)<12*h}if(a&&(m=y(b),n=A(b),ma(),!q&&(!r&&!s&&!t&&!u)&&(q=B(m,n,v[0],w[0])<4*h?c:e,r=B(m,n,v[1],w[1])<4*h?c:e,s=B(m,n,v[2],w[2])<4*h?c:e,t=B(m,n,v[3],w[3])<4*h?c:e,u=B(m,n,v[4],w[4])<4*h?c:e,(q||r||s||t||u)&&x()),q||r||s||t||u))B(m,n,v[0],w[0])<4*h?q=c:(q=e,x()),B(m,n,v[1],w[1])<4*h?r=c:(r=e,x()),B(m,n,v[2],w[2])<4*h?s=c:(s=e,x()),B(m,n,v[3],w[3])<4*h?t=c:(t=e,x()),B(m,n,v[4],w[4])<4*h?u=c:(u=e,
x())}
function la(){ea=c;da=e;fa=c;m=f/2-h/2;n=g/2-h/2;if(q||r||s||t||u){q||clearInterval(ha);if(!q&&!u)for(var b=document.getElementsByTagName("canvas"),a=0;a<b.length;)b[a].style.visibility="hidden",a++;q&&(document.getElementById("book").style.a=-1,document.getElementById("book").style.display="none",document.getElementById("exit").style.visibility="hidden",document.getElementById("settings").style.a=1E3,document.getElementById("settings").style.visibility="visible");s&&(document.getElementById("book").style.a=-1,
document.getElementById("book").style.display="none",document.getElementById("exit").style.visibility="hidden",removejscssfile("game.js","js"),b=document.getElementsByTagName("head")[0],a=document.createElement("script"),a.type="text/javascript",a.onload=function(){coop()},a.src="http://openedfire.com/coop.js",b.appendChild(a),document.getElementById("coop").style.visibility="visible");if(r){document.getElementById("settings").style.display="none";document.getElementById("book").style.a=-1;document.getElementById("book").style.display=
"none";document.getElementById("exit").style.visibility="hidden";removejscssfile("coop.js","js");document.getElementById("game1").style.visibility="visible";document.getElementById("i").style.left=f/2-document.getElementById("i").offsetWidth/2+"px";document.getElementById("i").style.visibility="visible";f=$(window).width();g=$(window).height();new Firebase("https://r1bx45ta4hw.firebaseio-demo.com/");document.getElementById("hG").style.display="block";document.getElementById("hR").style.display="block";
d=$(window).width();z=$(window).height();na="w";oa="s";pa="a";qa="d";ra=(new Date).getTime();C=[];D=[];E=[];F=[];sa=[];ta=[];ua=[];va();E[0]=2*G;F[0]=3*H;I=[];J=[];K=wa/6;M=xa/5;N=2*M;O=3*K;var d=window.innerWidth,z=window.innerHeight;document.getElementById("img").height=0.99*z;document.getElementById("img").width=d;zombies=[];ya=[];za=[];for(b=0;50>b;b++)sa[b]=Math.random()*f,ta[b]=Math.random()*g,ua[b]=Math.ceil(2*Math.random());Aa=new Image;Aa.src="http://www.openedfire.com/img/Decals/Crosshair.png";
Ba=new Image;Ba.src="http://www.openedfire.com/img/Map/Map.png";Ca=new Image;Ca.src="http://www.openedfire.com/img/Zombie/Zombie.png";Da=new Image;Da.src="http://www.openedfire.com/img/Zombie/Zombie2.gif";Ea=new Image;Ea.src="http://www.openedfire.com/img/Zombie/Zombie3.gif";Fa=new Image;Fa.src="http://www.openedfire.com/img/Human808/808.png";Ga=new Image;Ga.src="http://www.openedfire.com/img/Human71-M/Ti-M.png";Ha=new Image;Ha.src="http://www.openedfire.com/img/Decals/Decals.png";box=new Image;box.src=
"http://www.openedfire.com/img/Decals/Ingot.png";Ia=new Image;Ia.src="http://www.mudandblood.net/wiki/images/1/1f/Blood_splatter.png";Ja=new Image;Ja.src="http://www.openedfire.com/img/Decals/Mine.png";va();Ka=document.getElementById("game1");Ka.width=d;Ka.height=z;La=document.getElementById("splat");La.style.visibility="visible";La.width=d;La.height=z;y=d/2;A=z/2;Ma/=8500;for(b=0;1>b;b++)Na(Math.random()*d,Math.round(Math.random())*z);b=new Audio("sounds/OpenedFire.wav");b.addEventListener("ended",
function(){this.currentTime=0;this.play()},e);b.play();document.getElementById("b").onmousedown=function(a){Oa(a)};document.getElementById("b").onmousemove=function(a){m=Pa(a);n=Qa(a)};document.getElementById("b").onmouseup=function(){clearInterval(Ra)};document.getElementById("b").ontouchstart=function(a){a.preventDefault();a.preventDefault();500>(new Date).getTime()-Sa?(Sa=(new Date).getTime(),Oa(a)):(Sa=(new Date).getTime(),m=a.targetTouches[0].pageX,n=a.targetTouches[0].pageY,m<f/2&&n>g/4&&n<
g-g/4&&!P?(P=c,N=0,O=3*K):m>f/2&&n>g/4&&n<g-g/4?R||(R=c,N=3*M,O=3*K):n<g/2&&m>f/4&&m<f-f/4?n>S&&!Ta&&(Ta=c,N=2*M,O=0):n>g/2&&(m>f/4&&m<f-f/4)&&!Ua&&(Ua=c,N=2*M,O=4*K))};document.getElementById("b").ontouchmove=function(a){a.preventDefault()};document.getElementById("b").ontouchend=function(a){a.preventDefault();R=P=Ua=Ta=e};document.onkeypress=function(a){a=window.event||a;var b=String.fromCharCode(a.charCode);Va=b;if(32==a.keyCode||" "==b)0!=T.length?T[T.length]=y:T[T.length+1]=y,T[T.length]=A,T[T.length]=
m+(m-y),T[T.length]=n+(n-A),Wa[Wa.length]=T.length-1,setTimeout(function(){T.splice(Wa[0],1)},2E3);b==na&&A>S&&!Ta&&(Ta=c,N=2*M,O=0);b==oa&&A<z-100-S&&!Ua&&(Ua=c,N=2*M,O=4*K);b==pa&&y>S&&!P&&(P=c,N=0,O=3*K);b==qa&&y<d-100-S&&!R&&(R=c,N=3*M,O=3*K);"1"==b&&Xa();"2"==b&&Xa();Xa()};document.onkeyup=function(){"q"==Va&&0<U&&(U--,V+=50,100<V&&(V=100),document.getElementById("hG").style.width=0.9*playerhealth+"%");"e"==Va&&0<U&&(1==W?(console.log("gun change"),W=2,console.log("poop change"),U-=1,console.log("yay change")):
2==W?2<=U&&(W=3,U-=2):3==W&&3<=U&&(W=4,U-=3));R=P=Ua=Ta=e};X=Ka.getContext("2d");Ya=La.getContext("2d");$("#game1").c({x:4,y:4,rotation:2});X.fillRect(y,A,100,100);document.getElementById("i").onmousedown=function(){document.getElementById("i").style.visibility="hidden";var a="guest"+Math.floor(9999*Math.random()+500),b=prompt("Please enter a name",a);b==aa?Za=a:("andrew ;)"==b&&($a=50,V=1E4,Ma=0),"mike 8D"==b&&($a=1,V=999999,U=100),Za=b);console.log("Attempting to connect to server");ab=new WebSocket("ws://198.58.104.249:1035/multi542773");
ab.onopen=function(){console.log("Connected")};ab.onmessage=function(a){a=a.data.split(",");bb=a[1];cb=a[2];E=a[3];F=a[4]};ab.onclose=function(){console.log("Disconnected")};ha=setInterval(function(){A<S&&(Ta=e);S||(Ua=e);y<S&&(P=e);y<f-100-S||(R=e);if(0<T.length)for(var a=1;a<T.length;a+=4){var b,d;b=T[a]-T[a+2];d=T[a+1]-T[a+3];var z=d/b,L,l;if(0!=b){l=Math.atan(z);0<l&&(l*=-1);0>b?(L=30*Math.cos(l),T[a]+=L):(L=30*Math.cos(l),T[a]-=L,L*=-1);0>d?(l=30*Math.sin(l),T[a+1]-=l,l*=-1):(l=30*Math.sin(l),
T[a+1]+=l);for(b=0;b<C.length;b++)(T[a]>=f||T[a+1]>=g||0>=T[a]||0>=T[a+1])&&T.splice(a,4),b!=Wa[0]&&B(C[b],D[b],T[a],T[a+1])<S&&(Ya.drawImage(Ia,C[b],D[b],50,50),1==db[b]?0.5>Math.random()&&(C.splice(b,1),D.splice(b,1),I.splice(b,1),E.splice(b,1),F.splice(b,1),J.splice(b,1),db.splice(b,1)):0==db[b]?(C.splice(b,1),D.splice(b,1),I.splice(b,1),E.splice(b,1),F.splice(b,1),J.splice(b,1),db.splice(b,1)):0.2>Math.random()&&(C.splice(b,1),D.splice(b,1),I.splice(b,1),E.splice(b,1),F.splice(b,1),J.splice(b,
1),db.splice(b,1)),(1==W||3==W)&&T.splice(a,4),eb--,fb++,Y+=100*Math.random())}}if(0<C.length)for(a=0;a<C.length;a++)b=C[a]-y,d=D[a]-A,z=d/b,0!=b&&(l=Math.atan(z),0<l&&(l*=-1),0>b?(L=I[a]*Math.cos(l),C[a]+=L):(L=I[a]*Math.cos(l),C[a]-=L,L*=-1),0>d?(l=I[a]*Math.sin(l),D[a]-=l,l*=-1):(l=I[a]*Math.sin(l),D[a]+=l)),b=Math.abs(L),d=Math.abs(l),b<=d&&0<=l?("down"!=J[a]&&(E[a]=2*G,F[a]=4*H),J[a]="down"):b<d&&0>l?("up"!=J[a]&&(E[a]=2*G,F[a]=0),J[a]="up"):b>=d&&0<=L?("right"!=J[a]&&(E[a]=3*G,F[a]=3*H),J[a]=
"right"):b>d&&0>L&&("left"!=J[a]&&(E[a]=0,F[a]=3*H),J[a]="left"),B(y,A,C[a],D[a])<M&&(V-=0.05,document.getElementById("hG").style.width=0.9*V+"%");Ta&&(A-=$a);Ua&&(A+=$a);P&&(y-=$a);R&&(y+=$a);for(a=0;a<Z.length;a+=2)B(y,A,Z[a],Z[a+1])<M&&(Z.splice(a,2),U++);Math.random()<Ma&&(0.4>=Math.random()?Na(Math.random()*f,Math.round(Math.random())*g):Na(Math.round(Math.random())*f,Math.random()*g));Ma+=Ma/2E3;V-=0.01;document.getElementById("hG").style.width=0.9*V+"%";Y+=1E-7*Y+0.01;0>=V&&(alert("You Lose!"),
clearInterval(ha),window.location="http://openedfire.com");10>=V&&!gb?(gb=c,$("#game1").b("startRumble")):gb==c&&30<V&&($("#game1").b("stopRumble"),gb=e);0.001>Math.random()&&(Z[Z.length]=Math.random()*f,Z[Z.length]=Math.random()*g);hb?50>B(y,A,ib,jb)&&(hb=e,C=[],D=[],I=[],E=[],F=[],J=[],Y+=5*eb*(Math.random()+1),eb=0,V*=0.75):5E-4>Math.random()&&(hb=c,ib=Math.random()*f,jb=Math.random()*g);X.clearRect(0,0,f,g);hb&&X.drawImage(Ja,ib,jb,100,100);for(a=0;a<sa.length;a++)1>=ua[a]&&X.drawImage(Ha,0,0,
90,80,sa[a],ta[a],0.5*M,0.5*K);for(a=0;a<kb.length;a+=2);for(a=0;a<Z.length;a+=2)X.drawImage(box,Z[a],Z[a+1],40,40);X.fillStyle=1==W?"#ffff00":2==W||4==W?"#ff0000":"#c0c0c0";for(a=1;a<T.length;a+=4)X.fillRect(T[a],T[a+1],10,10);X.drawImage(Fa,N,O,M,K,y,A,M,K);X.drawImage(Ga,E,F,M,K,bb,cb,M,K);for(a=0;a<za.length;a++)X.drawImage(Ba,ya[a],za[a],0.9*S,0.9*S);for(a=0;a<C.length;a++)(E[a]>lb||F[a]>wa||0>E[a]||0>F[a])&&console.log(E[a]+", "+F[a]+": "+J[a]),0==db[a]?X.drawImage(Ca,E[a],F[a],G,H,C[a],D[a],
G,H):1==db[a]?X.drawImage(Da,E[a],F[a],G,H,C[a],D[a],G,H):X.drawImage(Ea,E[a],F[a],G,H,C[a],D[a],G,H);X.drawImage(Aa,m-1.5*h,n-1.2*h,2*h,2*h);mb+=1/(((new Date).getTime()-ra)/1E3);nb++;100<nb&&(ob=mb/100,nb=mb=0,pb=Math.round(ob),$a=2*(80/pb),qb=1.5*(80/pb));document.getElementById("stats").innerHTML="Supplies: "+U+"   Score: "+Math.floor(Y);ra=(new Date).getTime()},10);setInterval(function(){Ta?O=O<K?O+K:0:Ua?(O+=K,O>5*K&&(O=4*K)):R?N=N==3*M?N+M:N-M:P&&(N=0==N?N+M:N-M);for(var a=0;a<C.length;a++)"up"==
J[a]?F[a]=F[a]<H?F[a]+H:0:"down"==J[a]?(F[a]+=H,F[a]>5*H&&(F[a]=4*H)):"right"==J[a]?E[a]=E[a]==3*G?E[a]+G:E[a]-G:"left"==J[a]?E[a]=0>=E[a]?E[a]+0.8*G:E[a]-0.8*G:console.log("else")},500);Xa()}}t&&(document.getElementById("book").style.a=-1,document.getElementById("book").style.display="none",document.getElementById("exit").style.visibility="hidden",document.getElementById("highscores").style.visibility="visible",highscores());u&&(document.getElementById("book").style.a=110,document.getElementById("book").style.display=
"inline",document.getElementById("book").style.visibility="visible",document.getElementById("exit").style.visibility="visible")}else ma(),x()}function y(b){var a;a=b.pageX;if(0==a||a==aa)a=b.targetTouches[0].pageX;return a}function A(b){var a;a=b.pageY;if(0==a||a==aa)a=b.targetTouches[0].pageY;return a}function ma(){ba.clearRect(0,0,f,g);ba.fillStyle="rgba(225, 225, 225, 0.8)";ba.beginPath();ba.arc(m,n,h,0,2*Math.PI,c);ba.closePath();ba.fill()}
function x(){j.clearRect(0,0,f,g);var b=0,a=k;j.strokeStyle="#EEEEEE";if(fa){theta=0;if(a>h)for(;theta<=2*Math.PI;)j.beginPath(),j.arc(a*Math.cos(theta)+(f/2-h/2),a*Math.sin(theta)+(g/2-h/2),12*h/20,0,2*Math.PI,c),j.closePath(),j.stroke(),theta+=Math.PI/32;0<=k&&(k-=12*h/15)}else{if(k>=12*h-h){ea=e;j.strokeStyle="#333333";if(da){j.beginPath();j.arc(f/2-h/2,g/2-h/2,12*h,0,2*Math.PI,c);j.closePath();j.stroke();j.lineWidth=1;a*=1.1;theta=Math.PI/3.3;j.lineWidth=5;for(j.font="20px monospace";theta<=2*
Math.PI;)j.fillStyle="rgba(0, 0, 0, 1)",j.strokeStyle="#000000",j.beginPath(),v[b]=a*Math.cos(theta)+(f/2-h/2),w[b]=a*Math.sin(theta)+(g/2-h/2),0==b&&(j.drawImage(p[0],a*Math.cos(theta)+(f/2-h/2)-2*h,a*Math.sin(theta)+(g/2-h/2)-2*h,4*h,4*h),q&&(j.arc(v[0],w[0],3*h,0,2*Math.PI,c),j.fillStyle="white",j.fillText("SETTINGS",v[0]-50,w[0]+4*h))),1==b&&(j.drawImage(p[1],a*Math.cos(theta)+(f/2-h/2)-2*h,a*Math.sin(theta)+(g/2-h/2)-2*h,4*h,4*h),r&&(j.arc(v[1],w[1],3*h,0,2*Math.PI,c),j.fillStyle="white",j.fillText("PLAY",
v[1]-25,w[1]+4*h))),2==b&&(j.drawImage(p[2],a*Math.cos(theta)+(f/2-h/2)-2*h,a*Math.sin(theta)+(g/2-h/2)-2*h,4*h,4*h),s&&(j.arc(v[2],w[2],3*h,0,2*Math.PI,c),j.fillStyle="white",j.fillText("CO-OP",v[2]-30,w[2]+4*h))),3==b&&(j.drawImage(p[3],a*Math.cos(theta)+(f/2-h/2)-2*h,a*Math.sin(theta)+(g/2-h/2)-2*h,4*h,4*h),t&&(j.arc(v[3],w[3],3*h,0,2*Math.PI,c),j.fillStyle="white",j.fillText("HIGHSCORES",v[3]-60,w[3]+4*h))),4==b&&(j.drawImage(p[4],a*Math.cos(theta)+(f/2-h/2)-2*h,a*Math.sin(theta)+(g/2-h/2)-2*
h,4*h,4*h),u&&(j.arc(v[4],w[4],3*h,0,2*Math.PI,c),j.fillStyle="white",j.fillText("STORY",v[4]-30,w[4]+4*h))),j.closePath(),j.stroke(),theta+=2*Math.PI/5,b++}j.lineWidth=1}else{for(theta=0;theta<=2*Math.PI;)j.beginPath(),j.arc(a*Math.cos(theta)+(f/2-h/2),a*Math.sin(theta)+(g/2-h/2),12*h/20,0,2*Math.PI,c),j.closePath(),j.stroke(),theta+=Math.PI/32;k<=12*h-h/2&&(k+=12*h/15)}j.font=h/3+"px Arial"}}function B(b,a,d,z){var Q=0,ia=0,Q=b-d,ia=a-z;return Math.sqrt(Q*Q+ia*ia)}
var Ka,X,Ya,$a=2,ya,za,S=50,na="w",oa="s",qa="d",pa="a",gb=e,Ta=e,Ua=e,P=e,R=e,Aa,Ba,C,D,E=0,F=0,eb=0,I,qb=1.5,Ma=20,fb=0,bb,cb,V=100,Fa,Ha,sa,ta,ua,xa=227,wa=287,lb=238,K=54,M=48,H=289/6,G=47.6,Wa=[],N=120,O=0,J,db=[],Ca,ra=0,nb=0,mb=0,ob=0,kb=[7,0,9,0,7,1,9,1,7,2,9,2,7,3,9,3,7,4,9,4],Y=0,T=[],Z=[],U=0,Va,W=1,pb=80,Ra,La,Ia,Ja,ib,jb,Sa=(new Date).getTime(),hb=e,Ga,Da,Ea;
function va(){for(var b=g/S,a=0,d=0;d<=b;d++)za[d]=d*S,ya[d]=0,a++;b=f/S;for(d=0;d<=b;d++)ya[a]=d*S,za[a]=0,a++;b=f/S;for(d=0;d<=b;d++)ya[a]=S+d*S,za[a]=g-S,a++;b=g/S;for(d=0;d<=b;d++)ya[a]=f-S,za[a]=d*S,a++}
function rb(){var b=new Audio,a=document.createElement("source");a.type="sounds/Gun sounds/Pew(Gun1).wav";1==W?a.src="sounds/Gun sounds/Pew(Gun1).wav":2==W?a.src="sounds/Gun sounds/Bpgau(Gun2).wav":3==W?a.src="sounds/Gun sounds/PicPicPic(Gun3).wav":4==W&&(a.src="sounds/Gun sounds/TcTcTc(Gun4).wav");b.appendChild(a);b.play();console.log(Pa+", "+Qa+", "+W);0!=T.length?T[T.length]=y:T[T.length+1]=y;T[T.length]=A;T[T.length]=m+100*(m-y);T[T.length]=n+100*(n-A)}
function Oa(b){var a=new Audio,d=document.createElement("source");d.type="audio/wav";d.src="sounds/Gun sounds/Pew(Gun1).wav";a.appendChild(d);a.play();3==W||4==W?(rb(),clearInterval(Ra),Ra=setInterval(function(){rb()},100)):(a=new Audio,d=document.createElement("source"),d.type="audio/wav",1==W?d.src="sounds/Gun sounds/Pew(Gun1).wav":2==W?d.src="sounds/Gun sounds/Bpgau(Gun2).wav":3==W?d.src="sounds/Gun sounds/PicPicPic(Gun3).wav":4==W&&(d.src="sounds/Gun sounds/TcTcTc(Gun4).wav"),console.log(d.src),
a.appendChild(d),a.play(),0!=T.length?T[T.length]=y:T[T.length+1]=y,T[T.length]=A,T[T.length]=sb(b)+100*(sb(b)-y),T[T.length]=tb(b)+100*(tb(b)-A))}function sb(b){var a;a=b.pageX;if(0==a||a==aa)a=b.targetTouches[0].pageX;return a}function tb(b){var a;a=b.pageY;if(0==a||a==aa)a=b.targetTouches[0].pageY;return a}function Pa(b){var a;a=b.pageX;if(0==a||a==aa)a=b.targetTouches[0].pageX;return a}function Qa(b){var a;a=b.pageY;if(0==a||a==aa)a=b.targetTouches[0].pageY;return a}
function Na(b,a){I[eb]=Math.random()*qb;C[eb]=b;D[eb]=a;var d=Math.random();db[eb]=d<(0.6*Math.pow(Y,2)+10)/(Math.pow(Y,2)+1E7)?2:d<(0.8*Math.pow(Y,2)+10)/(Math.pow(Y,2)+1E5)?1:0;eb++}function B(b,a,d,z){var Q=0,ia=0,Q=b-d,ia=a-z;return Math.sqrt(Q*Q+ia*ia)}var ab,Za="";function Xa(){var b=Za+","+y+","+A+","+N+","+O;console.log("sending...");try{ab.send(b)}catch(a){}}function va(){for(var b=0;b<kb.length;b++);};