var contStep=0,optimalRate=80,resW=720,resH=480,canvas1,ctx1,ctx2,x,y,step=2,sidesx,sidesy,blocksize=50,upkey="w",downkey="s",rightkey="d",leftkey="a",rumble=!1,kup=!1,kdown=!1,kleft=!1,kright=!1,crosshairs,play1=!0,pattern,zx,zy,numZombies=0,zspeed,zspeedmax=1.5,difficulty=50,zombiesKilled=0,player=0,user2x,user2y,playerHealth=100,playerImage,rock,rx,ry,rt,frameOffset=26,imgWidth=227,imgHeight=287,img2Width=238,img2Height=289,frameHeight=54,frameWidth=48,frame2Height=img2Height/6,frame2Width=47.6,
g=[],fx=120,fy=0,fx2,fy2,zd,opponent=" ",zimg,time=0,total=0,totalRate=0,rate=0,walls=[7,0,9,0,7,1,9,1,7,2,9,2,7,3,9,3,7,4,9,4],score=0,missiles=[],interval2,gears=[],box1=0,pressed,gun=1,fRate=80,clicked=!1,fireInterval,myDataRef,splat,blood,bomb,bx,by,time2=(new Date).getTime(),bombOn=!1;function game2(){w=$(window).width();h=$(window).height();game(0,0,0,0)}
function game(a,b,c,f){myDataRef=new Firebase("https://r1bx45ta4hw.firebaseio-demo.com/");document.getElementById("hG").style.display="block";document.getElementById("hR").style.display="block";e=$(window).width();d=$(window).height();0!=a?(upkey=a,downkey=b,leftkey=c,rightkey=f):(upkey="w",downkey="s",leftkey="a",rightkey="d");time=(new Date).getTime();run();zx=[];zy=[];fx2=[];fy2=[];rx=[];ry=[];rt=[];initializeWalls();fx2[0]=2*frame2Width;fy2[0]=3*frame2Height;zspeed=[];zd=[];frameHeight=imgHeight/
6;frameWidth=imgWidth/5;fx=2*frameWidth;fy=3*frameHeight;var e=window.innerWidth,d=window.innerHeight;document.getElementById("img").height=0.99*d;document.getElementById("img").width=e;zombies=[];sidesx=[];sidesy=[];newRocks(50);crosshairs=new Image;crosshairs.src="http://www.openedfire.com/img/Decals/Crosshair.png";pattern=new Image;pattern.src="http://www.openedfire.com/img/Map/Map.png";zimg=new Image;zimg.src="http://www.openedfire.com/img/Zombie/Zombie.png";playerImage=new Image;playerImage.src=
"http://www.openedfire.com/img/Human808/808.png";rock=new Image;rock.src="http://www.openedfire.com/img/Decals/Decals.png";box=new Image;box.src="https://si0.twimg.com/profile_images/371772412/super-mario-bros-question-block_bigger.gif";blood=new Image;blood.src="http://www.mudandblood.net/wiki/images/1/1f/Blood_splatter.png";bomb=new Image;bomb.src="http://image.spreadshirt.com/image-server/v1/designs/11116745,width=178,height=178/Pixel-Bomb-%7C-Weapon.png";initializeWalls();canvas1=document.getElementById("game1");
canvas1.width=e;canvas1.height=d;splat=document.getElementById("splat");splat.style.visibility="visible";splat.width=e;splat.height=d;x=e/2;y=d/2;difficulty/=1E4;for(a=0;1>a;a++)newZombie(Math.random()*e,Math.round(Math.random())*d);a=new Audio("sounds/Opened Fire.wav");a.addEventListener("ended",function(){this.currentTime=0;this.play()},!1);a.play();document.getElementById("b").onmousedown=function(a){down2(a)};document.getElementById("b").onmousemove=function(a){move2(a)};document.getElementById("b").onmouseup=
function(a){up2(a)};document.getElementById("b").ontouchstart=function(a){a.preventDefault();tdown(a)};document.getElementById("b").ontouchmove=function(a){a.preventDefault();tmove(a)};document.getElementById("b").ontouchend=function(a){a.preventDefault();tup(a)};document.onkeypress=function(a){a=window.event||a;var b=String.fromCharCode(a.charCode);pressed=b;(32==a.keyCode||" "==b)&&throw2();b==upkey&&y>blocksize&&!kup&&(kup=!0,fx=2*frameWidth,fy=0);b==downkey&&y<d-100-blocksize&&!kdown&&(kdown=
!0,fx=2*frameWidth,fy=4*frameHeight);b==leftkey&&x>blocksize&&!kleft&&(kleft=!0,fx=0,fy=3*frameHeight);b==rightkey&&x<e-100-blocksize&&!kright&&(kright=!0,fx=3*frameWidth,fy=3*frameHeight);"1"==b&&(player=1,multi(),send());"2"==b&&(player=2,multi(),send());send()};document.onkeyup=function(){"q"==pressed&&0<box1&&(box1--,playerHealth+=50,100<playerHealth&&(playerHealth=100),document.getElementById("hG").style.width=0.9*playerhealth+"%");"e"==pressed&&0<box1&&(1==gun?(console.log("gun change"),gun=
2,console.log("poop change"),box1-=1,console.log("yay change")):2==gun?2<=box1&&(gun=3,box1-=2):3==gun&&3<=box1&&(gun=4,box1-=3));kright=kleft=kdown=kup=!1};ctx1=canvas1.getContext("2d");ctx2=splat.getContext("2d");$("#game1").jrumble({x:4,y:4,rotation:2});ctx1.fillRect(x,y,100,100);interval=setInterval(function(){postdraw()},10);setInterval(function(){reload()},500)}
function reload(){kup?fy=fy<frameHeight?fy+frameHeight:0:kdown?(fy+=frameHeight,fy>5*frameHeight&&(fy=4*frameHeight)):kright?fx=fx==3*frameWidth?fx+frameWidth:fx-frameWidth:kleft&&(fx=0==fx?fx+frameWidth:fx-frameWidth);for(var a=0;a<zx.length;a++)"up"==zd[a]?fy2[a]=fy2[a]<frame2Height?fy2[a]+frame2Height:0:"down"==zd[a]?(fy2[a]+=frame2Height,fy2[a]>5*frame2Height&&(fy2[a]=4*frame2Height)):"right"==zd[a]?fx2[a]=fx2[a]==3*frame2Width?fx2[a]+frame2Width:fx2[a]-frame2Width:"left"==zd[a]?fx2[a]=0>=fx2[a]?
fx2[a]+0.8*frame2Width:fx2[a]-0.8*frame2Width:console.log("else")}
function update(){y<blocksize&&(kup=!1);blocksize||(kdown=!1);x<blocksize&&(kleft=!1);x<w-100-blocksize||(kright=!1);if(0<missiles.length)for(var a=1;a<missiles.length;a+=4){var b,c;b=missiles[a]-missiles[a+2];c=missiles[a+1]-missiles[a+3];var f=c/b,e,d;if(0!=b){d=Math.atan(f);0<d&&(d*=-1);0>b?(e=30*Math.cos(d),missiles[a]+=e):(e=30*Math.cos(d),missiles[a]-=e,e*=-1);0>c?(d=30*Math.sin(d),missiles[a+1]-=d,d*=-1):(d=30*Math.sin(d),missiles[a+1]+=d);for(b=0;b<zx.length;b++)(missiles[a]>=w||missiles[a+
1]>=h||0>=missiles[a]||0>=missiles[a+1])&&missiles.splice(a,4),b!=g[0]&&dst(zx[b],zy[b],missiles[a],missiles[a+1])<blocksize&&(drawSplat(zx[b],zy[b]),zx.splice(b,1),zy.splice(b,1),zspeed.splice(b,1),fx2.splice(b,1),fy2.splice(b,1),zd.splice(b,1),(1==gun||3==gun)&&missiles.splice(a,4),numZombies--,zombiesKilled++,score+=100*Math.random())}}if(0<zx.length)for(a=0;a<zx.length;a++)b=zx[a]-x,c=zy[a]-y,f=c/b,0!=b&&(d=Math.atan(f),0<d&&(d*=-1),0>b?(e=zspeed[a]*Math.cos(d),zx[a]+=e):(e=zspeed[a]*Math.cos(d),
zx[a]-=e,e*=-1),0>c?(d=zspeed[a]*Math.sin(d),zy[a]-=d,d*=-1):(d=zspeed[a]*Math.sin(d),zy[a]+=d)),b=Math.abs(e),c=Math.abs(d),b<=c&&0<=d?("down"!=zd[a]&&(fx2[a]=2*frame2Width,fy2[a]=4*frame2Height),zd[a]="down"):b<c&&0>d?("up"!=zd[a]&&(fx2[a]=2*frame2Width,fy2[a]=0),zd[a]="up"):b>=c&&0<=e?("right"!=zd[a]&&(fx2[a]=3*frame2Width,fy2[a]=3*frame2Height),zd[a]="right"):b>c&&0>e&&("left"!=zd[a]&&(fx2[a]=0,fy2[a]=3*frame2Height),zd[a]="left"),dst(x,y,zx[a],zy[a])<frameWidth&&(playerHealth-=0.05,document.getElementById("hG").style.width=
0.9*playerHealth+"%");kup&&(y-=step);kdown&&(y+=step);kleft&&(x-=step);kright&&(x+=step);for(a=0;a<gears.length;a+=2)dst(x,y,gears[a],gears[a+1])<frameWidth&&(gears.splice(a,2),box1++);Math.random()<difficulty&&(0.4>=Math.random()?newZombie(Math.random()*w,Math.round(Math.random())*h):newZombie(Math.round(Math.random())*w,Math.random()*h));difficulty+=difficulty/2E3;playerHealth-=0.01;document.getElementById("hG").style.width=0.9*playerHealth+"%";score+=1E-7*score+0.01;0>=playerHealth&&(alert("You Lose!"),
clearInterval(interval),window.location="http://openedfire.com");30>=playerHealth&&!rumble?(rumble=!0,$("#game1").trigger("startRumble")):!0==rumble&&30<playerHealth&&($("#game1").trigger("stopRumble"),rumble=!1);0.001>Math.random()&&(gears[gears.length]=Math.random()*w,gears[gears.length]=Math.random()*h);bombOn?50>dst(x,y,bx,by)&&(alert("BOOM!!!"),bombOn=!1,zx=[],zy=[],zspeed=[],fx2=[],fy2=[],zd=[],score+=5*numZombies*(Math.random()+1),numZombies=0,playerHealth*=0.75):5E-4>Math.random()&&(bombOn=
!0,bx=Math.random()*w,by=Math.random()*h)}
function postdraw(){update();ctx1.clearRect(0,0,w,h);bombOn&&ctx1.drawImage(bomb,bx,by,100,100);for(var a=0;a<rx.length;a++)1>=rt[a]&&ctx1.drawImage(rock,0,0,90,80,rx[a],ry[a],0.5*frameWidth,0.5*frameHeight);for(a=0;a<walls.length;a+=2);for(a=0;a<gears.length;a+=2)ctx1.drawImage(box,gears[a],gears[a+1],40,40);ctx1.fillStyle=1==gun?"#ffff00":2==gun||4==gun?"#ff0000":"#c0c0c0";for(a=1;a<missiles.length;a+=4)ctx1.fillRect(missiles[a],missiles[a+1],10,10);ctx1.drawImage(playerImage,fx,fy,frameWidth,frameHeight,
x,y,frameWidth,frameHeight);ctx1.fillRect(user2x,user2y,50,50);ctx1.font="60px Arial";ctx1.fillText(opponent,user2x,user2y);for(a=0;a<sidesy.length;a++)ctx1.drawImage(pattern,sidesx[a],sidesy[a],0.9*blocksize,0.9*blocksize);for(a=0;a<zx.length;a++)(fx2[a]>img2Width||fy2[a]>imgHeight||0>fx2[a]||0>fy2[a])&&console.log(fx2[a]+", "+fy2[a]+": "+zd[a]),ctx1.drawImage(zimg,fx2[a],fy2[a],frame2Width,frame2Height,zx[a],zy[a],frame2Width,frame2Height);ctx1.drawImage(crosshairs,cx-1.5*c1R,cy-1.2*c1R,2*c1R,2*
c1R);totalRate+=1/(((new Date).getTime()-time)/1E3);total++;100<total&&(rate=totalRate/100,total=totalRate=0,fRate=Math.round(rate),step=2*(80/fRate),zspeedmax=1.5*(80/fRate));time=(new Date).getTime()}function drawSplat(a,b){ctx2.drawImage(blood,a,b,50,50)}
function initializeWalls(){for(var a=h/blocksize,b=0,c=0;c<=a;c++)sidesy[c]=c*blocksize,sidesx[c]=0,b++;a=w/blocksize;for(c=0;c<=a;c++)sidesx[b]=c*blocksize,sidesy[b]=0,b++;a=w/blocksize;for(c=0;c<=a;c++)sidesx[b]=blocksize+c*blocksize,sidesy[b]=h-blocksize,b++;a=h/blocksize;for(c=0;c<=a;c++)sidesx[b]=w-blocksize,sidesy[b]=c*blocksize,b++}
function fire(){var a=new Audio,b=document.createElement("source");b.type="audio/wav";1==gun?b.src="sounds/Gunsounds/Pew(Gun1).wav":2==gun?b.src="sounds/Gunsounds/Bdgau(Gun2).wav":3==gun?b.src="sounds/Gunsounds/PicPicPic(Gun3).wav":4==gun&&(b.src="sounds/Gunsounds/TcTcTc(Gun4).wav");a.appendChild(b);a.play();console.log(x2+", "+y2+", "+gun);0!=missiles.length?missiles[missiles.length]=x:missiles[missiles.length+1]=x;missiles[missiles.length]=y;missiles[missiles.length]=cx+100*(cx-x);missiles[missiles.length]=
cy+100*(cy-y)}function throw2(){0!=missiles.length?missiles[missiles.length]=x:missiles[missiles.length+1]=x;missiles[missiles.length]=y;missiles[missiles.length]=cx+(cx-x);missiles[missiles.length]=cy+(cy-y);g[g.length]=missiles.length-1;setTimeout(function(){missiles.splice(g[0],1)},2E3)}
function down2(a){clicked=!0;if(3==gun||4==gun)fire(),clearInterval(fireInterval),fireInterval=setInterval(function(){fire()},300);else{var b=new Audio,c=document.createElement("source");c.type="audio/wav";1==gun?c.src="sounds/Gunsounds/Pew(Gun1).wav":2==gun?c.src="sounds/Gunsounds/Bdgau(Gun2).wav":3==gun?c.src="sounds/Gunsounds/PicPicPic(Gun3).wav":4==gun&&(c.src="sounds/Gunsounds/TcTcTc(Gun4).wav");console.log(c.src);b.appendChild(c);b.play();0!=missiles.length?missiles[missiles.length]=x:missiles[missiles.length+
1]=x;missiles[missiles.length]=y;missiles[missiles.length]=tx(a)+100*(tx(a)-x);missiles[missiles.length]=ty(a)+100*(ty(a)-y)}}function tx(a){var b;b=a.pageX;if(0==b||null==b)b=a.targetTouches[0].pageX;return b}function ty(a){var b;b=a.pageY;if(0==b||null==b)b=a.targetTouches[0].pageY;return b}function isValidCode(a){return-1<$.inArray(a,codes)}function move2(a){cx=x2(a);cy=y2(a)}
function tdown(a){a.preventDefault();if(500>(new Date).getTime()-time2)return time2=(new Date).getTime(),down2(a),0;time2=(new Date).getTime();cx=a.targetTouches[0].pageX;cy=a.targetTouches[0].pageY;cx<w/2&&cy>h/4&&cy<h-h/4&&!kleft?(kleft=!0,fx=0,fy=3*frameHeight):cx>w/2&&cy>h/4&&cy<h-h/4?kright||(kright=!0,fx=3*frameWidth,fy=3*frameHeight):cy<h/2&&cx>w/4&&cx<w-w/4?cy>blocksize&&!kup&&(kup=!0,fx=2*frameWidth,fy=0):cy>h/2&&(cx>w/4&&cx<w-w/4)&&!kdown&&(kdown=!0,fx=2*frameWidth,fy=4*frameHeight)}
function tup(){kright=kleft=kdown=kup=!1}function tmove(){}function up2(){clearInterval(fireInterval);clicked=!1}function x2(a){var b;b=a.pageX;if(0==b||null==b)b=a.targetTouches[0].pageX;return b}function y2(a){var b;b=a.pageY;if(0==b||null==b)b=a.targetTouches[0].pageY;return b}function newZombie(a,b){zspeed[numZombies]=Math.random()*zspeedmax;zx[numZombies]=a;zy[numZombies]=b;numZombies++}
function newRocks(a){for(var b=0;b<a;b++)rx[b]=Math.random()*w,ry[b]=Math.random()*h,rt[b]=Math.ceil(2*Math.random())}function dst(a,b,c,f){var e=0,d=0,e=a-c,d=b-f;return Math.sqrt(e*e+d*d)}function multi(){}function send(){sendMessage(userName+","+x+","+y)}
var ws,userName="",sendMessage=function(){},safe_tags=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},getUsername=function(){var a="guest"+Math.floor(9999*Math.random()+500),b=prompt("Please enter a name",a);if(null==b)return a;"andrew ;)"==b&&(step=50,playerHealth=1E4,difficulty=0);"mike 8D"==b&&(step=1,playerHealth=999999,box1=100);return b};myDataRef.on("child_added",function(a){console.log("retrieved");a.val()});
function run(){userName=getUsername();console.log("Attempting to connect to server")}
function reassignKeys(a,b,c,f){upkey=a;downkey=b;rightkey=c;leftkey=f;removejscssfile("coop.js","js");document.getElementById("settings").style.visibility="hidden";document.getElementById("myCanvas").style.visibility="hidden";document.getElementById("myCanvas2").style.visibility="hidden";document.getElementById("myCanvas3").style.visibility="hidden";document.getElementById("game1").style.visibility="visible";game(upkey,downkey,rightkey,leftkey)}
function multiplyall(a,b){for(var c=0;c<a.length;c++)a[c]*=b}function initializeWalls(){for(var a=0;a<walls.length;a++);}var is={ie:"Microsoft Internet Explorer"==navigator.appName,java:navigator.javaEnabled(),ns:"Netscape"==navigator.appName,ua:navigator.userAgent.toLowerCase(),version:parseFloat(navigator.appVersion.substr(21))||parseFloat(navigator.appVersion),win:"Win32"==navigator.platform};is.mac=0<=is.ua.indexOf("mac");0<=is.ua.indexOf("opera")&&(is.ie=is.ns=!1,is.opera=!0);
0<=is.ua.indexOf("gecko")&&(is.ie=is.ns=!1,is.gecko=!0);
